config/routes.rb
Rails.application.routes.draw do
  root 'posts#index'
  resources :posts, :post_offices, :emails, :tracks

  devise_for :users, :admins
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/email.rb
class Email < ApplicationRecord
end

app/models/post.rb
class Post < ApplicationRecord
  has_attached_file :image, styles: { medium: "500x500>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\Z/
end

app/models/post_office.rb
class PostOffice < ApplicationRecord
  require 'rubygems'
  require 'mechanize'
  require 'open-uri'
  require 'nokogiri'
  before_create :post_office_finder

  def post_office_finder
    mechanize = Mechanize.new
    page = mechanize.get('http://belindex.5balov.net/')

    form = page.form()
    form.text = self.postcode
    page = form.submit
    link = page.links[1]

    page = Nokogiri::HTML(open("#{link.uri}"))
    contact_data  = page.css("p")[0].text
    addresses = page.css("p")[1].text
    self.post_office_info = "#{contact_data} \n#{addresses}"

  end
end

app/models/track.rb
class Track < ApplicationRecord
  require 'rubygems'
  require 'nokogiri'
  require 'open-uri'
  before_create :tracker

  def tracker
    self.track_info = "Mail № #{self.track_number}\n"
    page = Nokogiri::HTML(open("http://www.trackitonline.ru/?tn=#{self.track_number}"))
    data = Hash.new
    page.css("div.media").each do |data|
      title = data.css("b").text
      date = data.css("p")[0].text
      post_office = data.css("p")[1].text
      self.track_info += date + "; " + post_office + "; " + title + "\n"
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/emails_controller.rb
class EmailsController < ApplicationController
  before_action :set_email, only: [:show, :edit, :update, :destroy]

  # GET /emails
  # GET /emails.json
  def index
    @emails = Email.all
  end

  # GET /emails/1
  # GET /emails/1.json
  def show
  end

  # GET /emails/new
  def new
    @email = Email.new
  end

  # GET /emails/1/edit
  def edit
  end

  # POST /emails
  # POST /emails.json
  def create
    @email = Email.new(email_params)

    respond_to do |format|
      if @email.save
        format.html { redirect_to @email, notice: 'Email was successfully created.' }
        format.json { render :show, status: :created, location: @email }
      else
        format.html { render :new }
        format.json { render json: @email.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /emails/1
  # PATCH/PUT /emails/1.json
  def update
    respond_to do |format|
      if @email.update(email_params)
        format.html { redirect_to @email, notice: 'Email was successfully updated.' }
        format.json { render :show, status: :ok, location: @email }
      else
        format.html { render :edit }
        format.json { render json: @email.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /emails/1
  # DELETE /emails/1.json
  def destroy
    @email.destroy
    respond_to do |format|
      format.html { redirect_to emails_url, notice: 'Email was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_email
      @email = Email.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def email_params
      params.require(:email).permit(:to, :user_full_name, :addressee, :text)
    end
end

app/controllers/post_offices_controller.rb
class PostOfficesController < ApplicationController
    def new
        @post_office = PostOffice.new
    end

    def show
        @post_office = PostOffice.find(params[:id])
    end

    def create
      @post_office = PostOffice.new(post_office_params)
      if @post_office.save
        flash[:success] = "Success!"
        redirect_to @post_office
      else
        flase[:error] = @post_office.errors.full_messages
        redirect_to @post_office
      end
    end

    private
    def post_office_params
      params.require(:post_office).permit(:postcode, :post_office_info)
    end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def new
      @post = Post.new
  end

  def filename
    syms = ['a'..'z','A'..'Z','0'..'9'].map{ |range| range.to_a }.flatten
    @description = (0...8).map{ syms[ rand(syms.size) ] }.join
  end

  def index
    @posts = Post.all
  end

  def show
    @post = Post.find(params[:id])
  end

  def destroy
  @post = Post.find(params[:id])
  @post.destroy

  redirect_to posts_path
end

  def create
    @post = Post.new(permit_post)
    if @post.save
      flash[:success] = "Success!"
      redirect_to post_path(@post)
    else
      flase[:error] = @post.errors.full_messages
      redirect_to new_post_path
    end
  end

  private
  def permit_post
    filename
    params.require(:post).permit(:title,:image, :description)
  end

end

app/controllers/tracks_controller.rb
class TracksController < ApplicationController
  def new
    @track = Track.new
  end

  def show
    @track = Track.find(params[:id])
  end

  def create
    @track = Track.new(track_params)
    if @track.save
      flash[:success] = "Success!"
      redirect_to @track
    else
      flase[:error] = @track.errors.full_messages
      redirect_to @track
    end
  end

  private
  def track_params
    params.require(:track).permit(:track_number, :track_info)
  end
end

app/controllers/user_controller.rb
class UserController < ApplicationController

  after_create :send_admin_mail
  def send_admin_mail
    flash[:success] = "Success!"
    #UserMailer.send_new_user_message(self).deliver
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/emails_helper.rb
module EmailsHelper
end

app/helpers/post_offices_helper.rb
module PostOfficesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/tracks_helper.rb
module TracksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>JustMail</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

      <!-- Navigation -->
      <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
          <div class="container">
              <!-- Brand and toggle get grouped for better mobile display -->
              <div class="navbar-header">
                  <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                      <span class="sr-only">Toggle navigation</span>
                      <span class="icon-bar"></span>
                      <span class="icon-bar"></span>
                      <span class="icon-bar"></span>
                  </button>
                  <%= link_to "Home", root_url, class: "navbar-brand" %>
              </div>
              <!-- Collect the nav links, forms, and other content for toggling -->
              <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1" style="float:center">
                  <ul class="nav navbar-nav" >

                      <li>
                        <%= link_to "Track mail", new_track_path %>
                      </li>
                      <li>
                        <%= link_to "Find post office", new_post_office_path %>
                      </li>
                      <%- if current_admin %>
                      <li>
                          <%= link_to "New Post", new_post_path %>
                      </li>
                      <li>
                        <%= link_to "Send email", new_email_path%>
                      </li>
                      <li>
                          <%= link_to "Logout", destroy_admin_session_path, method: :delete, confirm: "Are you sure?" %>
                      </li>
                      <%- elsif current_user %>
                      <li>
                        <%= link_to "Send email", new_email_path%>
                      </li>
                      <li>
                          <%= link_to "Logout", destroy_user_session_path, method: :delete, confirm: "Are you sure?" %>
                      </li>
                      <%- else %>
                      <li>
                          <%= link_to "Login as user", new_user_session_path %>
                      </li>
                      <li>
                          <%= link_to "Login as admin", new_admin_session_path %>
                      </li>
                      <li style="float:right">
                        <%= link_to "Register", new_user_registration_path %>
                      </li>
                      <% end %>


                  </ul>
              </div>
              <!-- /.navbar-collapse -->
          </div>
          <!-- /.container -->
      </nav>

      <!-- Page Content -->
      <div class="container">

          <div class="row">
              <div class="col-lg-12 text-center">
                <% flash.each do |a, b| %>
                  <div class="alert alert-success"> <%= b %> </div>
                  <% end %>
                  <%= yield %>
              </div>
          </div>
          <!-- /.row -->
      </div>
      <!-- /.container -->
      <style>body{padding-top:70px;}</style>
  </body>

</html>

app/views/post_offices/new.html.erb
<h1>Post office</h1>

<%= form_for :post_office, url: post_offices_path do |f| %>
  <p>
    <%= f.label :postcode %><br>
    <%= f.text_field :postcode %>
  </p>

  <p>
    <%= f.submit "track" %>
  </p>
<% end %>

app/views/post_offices/show.html.erb
<p>
  <strong>Postcode:</strong>
  <%= @post_office.postcode %>
</p>


  <strong>Post office information</strong>
  <%= simple_format(@post_office.post_office_info) %>

app/views/posts/index.html.erb
<% @posts.each do |post| %>
  <div class="white">
    <p><font size="5"><b><%= post.title %></b></font>
    <br>
    <%= image_tag post.image.url(:medium) %>
    <br>
    <%= post.description %>

      <%- if current_admin %>
    <br>
    <%= link_to 'Destroy', post_path(post),
              method: :delete,
              data: { confirm: 'Are you sure?' } %>
        <% end %>
    </p>
  </div>
<% end %>

app/views/posts/new.html.erb
<h2>New Post</h2>
<hr>

<%= form_for @post, html: { multipart: true } do |form| %>

  <%= form.label :title %>
  <br>
  <%= form.text_field :title %>
  <br>
  <%= form.label :image %>
  <center>
  <%= form.file_field :image %>
  </center>
  <br>
  <%= form.label :description %>
  <br>
  <%= form.text_area :description %>
  <br>
  <%= form.submit %>

  <% end %>

app/views/posts/show.html.erb
<p><font size="5"><b><%= @post.title %></b></font>
<br>
<%= image_tag @post.image.url(:medium)  %>
<br>
<%= @post.description %>
<br>

app/views/tracks/new.html.erb
<h1>Track Mail</h1>

<%= form_for :track, url: tracks_path do |f| %>
  <p>
    <%= f.label :track_number %><br>
    <%= f.text_field :track_number %>
  </p>

  <p>
    <%= f.submit "track" %>
  </p>
<% end %>

app/views/tracks/show.html.erb
<div align="left">
<p>
  <strong>track number:</strong>
  <%= @track.track_number %>
</p>

<p>
  <strong>track info:</strong>
    <%= simple_format(@track.track_info) %>
</p>
</div>